name: GitHub Actions Demo
on: 
  push:
    branches: main
    paths-ignore: '.github/**'
      
  pull_request:
    branches: 
    - main
  schedule:
    - cron: "15 06 * * 0"

  workflow_dispatch:
    

    
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event ${{ github.event_name }}"
      - uses: actions/checkout@v1
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      - run: ls -R
  
  share-output:
    runs-on: ubuntu-latest
    steps: 
    - name: Set the date
      id: date
      run: | 
        echo "date=${{date}}" >> GITHUB_OUTPUT
    - name: Print
      run: echo "Date: ${{ steps.date.outputs.date }}"
