name: "Reuse other workflow"

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "@hagl"
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: print greeting time
        run: |
          echo "Hello ${{ needs.call-workflow.outputs.current-time }}"
